AEON_MILLIS = 0
AEON_MICROS = 1

AEON_KEYBOARD_STATE_DOWN = True
AEON_KEYBOARD_STATE_UP = False
AEON_MOUSE_STATE_DOWN = True
AEON_MOUSE_STATE_UP = False

AEON_STATE_CAPTURE_KEYBOARD = 200
AEON_STATE_CAPTURE_MOUSE = 201

# Mouse constants
AEON_MOUSE_LMB = 0
AEON_MOUSE_MMB = 1 # Middle/scroll button
AEON_MOUSE_RMB = 2
AEON_MOUSE_SCROLL_UP = 3
AEON_MOUSE_SCROLL_DOWN = 4
AEON_MOUSE_SCROLL_PRESSED_UP = 35
AEON_MOUSE_SCROLL_PRESSED_DOWN = 36

# Keyboard constants
AEON_KEY_LEFT = "100"
AEON_KEY_RIGHT = "102"
AEON_KEY_UP = "101"
AEON_KEY_DOWN = "103"

AEON_KEY_PAGE_UP = "104"
AEON_KEY_PAGE_DOWN = "105"
AEON_KEY_HOME = "106"
AEON_KEY_END = "107"
AEON_KEY_INSERT = "108"

AEON_KEY_SHIFT = "112"
AEON_KEY_RIGHT_SHIFT = "113"
AEON_KEY_CTRL = "114"
AEON_KEY_RIGHT_CTRL = "115"
AEON_KEY_ALT = "116"
AEON_KEY_RIGHT_ALT = "117"

AEON_KEY_BACKSPACE = "\x08"
AEON_KEY_ESC = "esc"
AEON_KEY_DELETE = "\x7f"
AEON_KEY_TAB = "tab"

AEON_KEY_SPACE = "space"

AEON_KEY_1 = "1"
AEON_KEY_2 = "2"
AEON_KEY_3 = "3"
AEON_KEY_4 = "4"
AEON_KEY_5 = "5"
AEON_KEY_6 = "6"
AEON_KEY_7 = "7"
AEON_KEY_8 = "8"
AEON_KEY_9 = "9"
AEON_KEY_0 = "0"

AEON_KEY_F1 = "F1"
AEON_KEY_F2 = "F2"
AEON_KEY_F3 = "F3"
AEON_KEY_F4 = "F4"
AEON_KEY_F5 = "F5"
AEON_KEY_F6 = "F6"
AEON_KEY_F7 = "F7"
AEON_KEY_F8 = "F8"
AEON_KEY_F9 = "F9"
AEON_KEY_F10 = "F10"
AEON_KEY_F11 = "F11"
AEON_KEY_F12 = "F12"